services:

  frontend:
    container_name: tdfs-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 8080:80
    restart: always
    depends_on:
      - nginx

  nginx:
    container_name: tdfs-nginx
    image: nginx:alpine
    ports:
      - 8000:80
    working_dir: /var/www/backend
    volumes:
      - ./backend:/var/www/backend
      - ./nginx:/etc/nginx/conf.d/
    restart: always
    depends_on:
      - php

  php:
    container_name: tdfs-php
    build:
      context: backend
      dockerfile: Dockerfile
    working_dir: /var/www/backend
    volumes:
      - ./backend:/var/www/backend
    restart: always
    depends_on:
      - postgres

  postgres:
    container_name: tdfs-postgres
    image: postgres:16.9-bullseye
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=backend
    ports:
      - 6543:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always
