services:
  php-apache:
    container_name: tdfs-php841
    build:
      context: backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - 8080:80
    # volumes:
    #   - ./backend:/var/www/html
    restart: always
    depends_on:
      - postgres

  postgres:
    container_name: tdfs-postgres
    image: postgres:16.9-bullseye
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=backend
    ports:
      - 6543:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always
