services:
  php:
    container_name: tdfs-php841
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/applicacao
    restart: always

  postgres:
    container_name: tdfs-postgres
    image: postgres:16.9-bullseye
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=backend
    ports:
      - 6543:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always
